### ISSUE TITLE
Switch to hosting on mbtashutdowns.info

### ISSUE THREAD

**Issue by devinmatte** [transitmatters/shutdown-tracker#13]
We purchased mbtashutdowns.info, we should host there for the production release

**Comment by devinmatte** [comment]
Frontend: mbtashutdowns.info
Backend: shutdowns.labs.transitmatters.org

The .ics files will point to the backend, so the url should be human readable

**Comment by nathan-weinberg** [comment]
@devinmatte If we want to launch May 7th should we switch over before then?

**Comment by devinmatte** [comment]
Yep, I reached out to @mathcolo for help because I'm struggling to get things happy

**Comment by mathcolo** [comment]
Will look tonight!
