### ISSUE TITLE
Add back button to shutdown details page

### ISSUE THREAD

**Issue by colbychaskell** [transitmatters/shutdown-tracker#14]
After clicking on the details for a shutdown, there doesn't seem to be an obvious way to go back to the initial screen with the graph of shutdown segments. 

A few options for this could be one or all of these:
- Add a back/exit button to the details view so that it can be closed
- Return to the graph view if you click on a different line in the top menu
- Return to the graph if you click the page title

**Comment by devinmatte** [comment]
This along with #4 should be a priority. I do think we can soft launch once those two are done
