### ISSUE TITLE
Update Shutdown Dates

### ISSUE THREAD

**Issue by skaplan-dev** [transitmatters/shutdown-tracker#21]
(see @skaplan-dev for link to slides)

We have a new deck of dates we can expect shutdowns to happen! We should update our const file to reflect these changes.

**Comment by devinmatte** [comment]
We can update using the following posts:

- https://www.mbta.com/news/2024-04-22/may-service-changes-mbta-continues-work-improve-reliability-across-the-system
- https://www.mbta.com/news/2024-03-15/april-service-changes-mbta-continues-work-improve-reliability-across-the-system
- https://www.mbta.com/news/2024-02-23/march-service-changes-mbta-continues-repair-work-improve-reliability-across-the
- https://www.mbta.com/news/2024-01-19/february-service-changes-update-mbta-continue-repair-work-improve-and-deliver-more

**Comment by devinmatte** [comment]
Updated based on officially announced shutdown dates
