### ISSUE TITLE
Add context for the graph dates on the shutdown details page

### ISSUE THREAD

**Issue by colbychaskell** [transitmatters/shutdown-tracker#23]
I'm not sure I understand the date labels on the x-axis for the shutdown details (i.e. the travel times graph). 

I assume the data after the shutdown corresponds to dates after shutdown and the before data corresponds to dates before the shutdown, but the values are displayed as if they are from the same dates (according to the x-axis label). 

Not sure how this is a bug or if the axes just need to be labelled differently.

**Comment by skaplan-dev** [comment]
Those dates correspond to the dates of the shutdown. But yeah we should figure out a way to display the proper range
