### ISSUE TITLE
Add Home Page for Shutdown Tracker

### ISSUE THREAD

**Issue by skaplan-dev** [transitmatters/shutdown-tracker#26]
lets make a nice home page :)

**Comment by devinmatte** [comment]
Show the next shutdown for each line, so people know at a glance when the next shutdown is

**Comment by cdwhitt** [comment]
Kiiiinda similar (in terms of providing an overview) to the data dashboard I'm assuming?
<img width="1081" alt="Screenshot 2024-04-06 at 10 24 43 PM" src="https://github.com/transitmatters/shutdown-tracker/assets/47030097/1ccb7443-9996-4aff-864b-c4b33e5b9aff">

**Comment by devinmatte** [comment]
Do we still want this?
