### ISSUE TITLE
Add router and create deep links

### ISSUE THREAD

**Issue by skaplan-dev** [transitmatters/shutdown-tracker#4]
To make sharing this tool easier, we should create routes and deep links.

We can use file-based routing with the [TanStack Router Vite plugin](https://tanstack.com/router/v1/docs/quick-start#using-file-based-route-generation--vite). 

```
/
    /{line}
    /{line}?fr_id=1234&to_id=1234&start_date=DD-MM-YYYY&end_date=DD-MM-YYYY ##details page
```

**Comment by cdwhitt** [comment]
🥇
