### ISSUE TITLE
.ics calendar exports?

### ISSUE THREAD

**Issue by idreyn** [transitmatters/shutdown-tracker#6]
Someone on Twitter is making a [very nice static calendar](https://twitter.com/velvetsuite/status/1749495224269684914/photo/1) of 2024 shutdowns and the thought arose in Slack...why not provide a Google Calendar (or something) that users can subscribe to from this app?

Tagging @mathcolo because I'm willing to bet he knows a thing or two about open calendar formats

**Comment by devinmatte** [comment]
Backend is ready, need to add a frontend button to link to it `https://shutdowns.labs.transitmatters.org/calendar` for people to try it
